package laJuegoteca.gui;

import java.util.Date;
import javax.swing.JOptionPane;
import laJuegoteca.beans.Juego;
import laJuegoteca.logica.LogicaNegocio;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;


/**
 *
 * @author david
 */
public class DialogoAgregarJuego extends javax.swing.JDialog {
    //Es un diálogo que extiende desde la pantalla principal, por lo que debemos declarar la misma.
    private PantallaPrincipal pantallaPrincipal;
    /** Creates new form DialogoAgregarJuego */
    public DialogoAgregarJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pantallaPrincipal = (PantallaPrincipal)parent;
        initComponents();
        //Utilizamos el validationPanel para asegurarnos de que llenamos TODOS los campos.
        //No he tenido en cuenta los campos género, plataforma y fecha ya que de no elegir, se quedan los que aparecen por defecto.
        ValidationGroup group = validationPanel.getValidationGroup();
        group.add(jTextFieldTitulo, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextFieldCompania, StringValidators.REQUIRE_NON_EMPTY_STRING);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jComboBoxPlataforma = new javax.swing.JComboBox<>();
        jTextFieldCompania = new javax.swing.JTextField();
        jSpinnerLanzamiento = new javax.swing.JSpinner();
        jButtonAgregar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        validationPanel.setOpaque(false);
        jPanel1.add(validationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 330, 20));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Añade un nuevo juego a La Juegoteca!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, 350, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Título:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 43, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Género:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 83, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Plataforma:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 123, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Compañía:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 163, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Lanzamiento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 203, -1, -1));

        jTextFieldTitulo.setName("Título"); // NOI18N
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 40, 288, -1));

        jComboBoxPlataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PlayStation", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5", "Game Boy", "Nintendo DS", "Nintendo 3DS", "NES", "SNES", "Nintendo 64", "Nintendo GameCube", "Nintendo Wii", "Nintendo WiiU", "Nintendo Switch", "Xbox", "Xbox 360", "Xbox One", "Xbox Series X", "PC", "Móvil" }));
        jPanel1.add(jComboBoxPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 120, 288, -1));

        jTextFieldCompania.setName("Compañía"); // NOI18N
        jTextFieldCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCompaniaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCompania, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 160, 288, -1));

        jSpinnerLanzamiento.setModel(new javax.swing.SpinnerDateModel());
        jPanel1.add(jSpinnerLanzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 200, 288, -1));

        jButtonAgregar.setText("Añadir");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción - Aventura", "Action RPG", "Aventura", "Aventura gráfica", "Carreras", "Deportes", "Estrategia", "Metroidvania", "Mundo abierto", "Musical", "Novela Visual", "Película interactiva", "Plataformas", "Puzzles", "Roguelike", "RPG", "Sigilo", "Simulador", "Survival", "Survival Horror", "Shooter", "Terror" }));
        jPanel1.add(jComboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 80, 288, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laJuegoteca/gui/imgs/fondodesenfocado.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 410, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCompaniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompaniaActionPerformed
        
    private boolean validarFormulario(){
        //Aparte del método de validación heredado por validationPanel, he implementado otro método de validación manual para los campos afectados
        //mediante el cual aparece un diálogo informativo en caso de intentar aceptar sin rellenar los campos.
         String titulo = jTextFieldTitulo.getText();
         if (titulo == null || "".equals(titulo)){
             JOptionPane.showMessageDialog(this, "El campo título no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }
         String compania = jTextFieldCompania.getText();
         if (compania == null || "".equals(compania)){
             JOptionPane.showMessageDialog(this, "El campo compañía no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }
        return true;
    }
    
    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        //El botón agregar recogerá el texto y los valores de las diferentes jTextField, jComboBox y jSpinner...
        String titulo = jTextFieldTitulo.getText();
        String genero = (String) jComboBoxGenero.getSelectedItem();
        String plataforma = (String)jComboBoxPlataforma.getSelectedItem();
        String compania = jTextFieldCompania.getText();
        Date lanzamiento = (Date)jSpinnerLanzamiento.getValue();
        //...creará un objeto juego pasándole estos parámetros recogidos...
        Juego juego = new Juego(titulo, genero, plataforma, compania, lanzamiento);
        if (validarFormulario()){
            //Y, si valida el formulario, los agrega a la lista (y a la tabla) y sale un mensaje de confirmación.
            JOptionPane.showMessageDialog(this, "Juego añadido correctamente.");
            LogicaNegocio.agregarJuego(juego);
        }
        dispose();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        //Botón para cerrar el diálogo sin realizar ninguna acción.
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JComboBox<String> jComboBoxPlataforma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerLanzamiento;
    private javax.swing.JTextField jTextFieldCompania;
    private javax.swing.JTextField jTextFieldTitulo;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables

}
