
package laJuegoteca.gui;

//Todos los imports que vamos a utilizar.
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import laJuegoteca.beans.Juego;
import laJuegoteca.gui.tablemodels.JuegosTableModel;
import laJuegoteca.logica.LogicaNegocio;
/**
 *
 * @author david
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    //Dentro de la clase PantallaPrincipal vamos a declarar estas dos variables, ya que las usaremos en distintos métodos.
    private DefaultTableModel dtm = new DefaultTableModel();
    private TableRowSorter <DefaultTableModel> sorter;
    
    /**
     * Creates new form PantallaPrincipal
     * 
     */
    public PantallaPrincipal() {
        //En la pantalla principal iniciaremos los componentes...
        initComponents();
        //Asociaremos una imagen al icono de nuestra aplicación...
        this.setIconImage(new ImageIcon(getClass().getResource("/laJuegoteca/gui/imgs/icono.jpg")).getImage());
        //Le daremos a nuestra tabla un modelo que coja la lista de juegos a través de nuestra lógica de negocio..
        jTableJuegos.setModel(new JuegosTableModel(LogicaNegocio.getListaJuegos()));
        //Y refrescaremos la tabla.
        refrescarTabla();
    }

    private void refrescarTabla(){
        //El método REFRESCAR TABLA básicamente actualizará la tabla vista en pantalla cada vez que realicemos alguna acción.
        //Llamaremos a este método en prácticamente todas las acciones.
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Título","Género","Plataforma","Compañía","Lanzamiento"});
        List<Juego> listaJuegos = LogicaNegocio.getListaJuegos();
        for (Juego juego: listaJuegos){
            dtm.addRow(juego.toArrayString());
        }
        jTableJuegos.setModel(dtm);
        
        //También he incluido el sorter, para permitir ordenar las diferentes columnas, dentro del método refrescar tabla.
        sorter = new TableRowSorter<>(dtm);
        jTableJuegos.setRowSorter(sorter);
        List<SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new SortKey (0,SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJuegos = new javax.swing.JTable();
        jButtonAgregarJuego = new javax.swing.JButton();
        jButtonGuardarDatos = new javax.swing.JButton();
        jButtonCargarDatos = new javax.swing.JButton();
        jTextFiltrar = new javax.swing.JTextField();
        Título = new javax.swing.JButton();
        jButtonFGenero = new javax.swing.JButton();
        jButtonFPlataforma = new javax.swing.JButton();
        jButtonFCompania = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laJuegoteca/gui/imgs/lajuegotecaredimensionado.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 420, 60));

        jTableJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableJuegos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 567, 261));

        jButtonAgregarJuego.setText("Añadir juego");
        jButtonAgregarJuego.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonAgregarJuegoFocusGained(evt);
            }
        });
        jButtonAgregarJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAgregarJuegoMouseEntered(evt);
            }
        });
        jButtonAgregarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarJuegoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 220, 80));

        jButtonGuardarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laJuegoteca/gui/imgs/imagenboton2.png"))); // NOI18N
        jButtonGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 222, 130));

        jButtonCargarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laJuegoteca/gui/imgs/imagenboton.png"))); // NOI18N
        jButtonCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 222, -1));
        jPanel1.add(jTextFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 540, -1));

        Título.setText("Título");
        Título.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TítuloActionPerformed(evt);
            }
        });
        jPanel1.add(Título, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 120, 30));

        jButtonFGenero.setText("Género");
        jButtonFGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 120, 30));

        jButtonFPlataforma.setText("Plataforma");
        jButtonFPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFPlataformaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 120, 30));

        jButtonFCompania.setText("Compañía");
        jButtonFCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFCompaniaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFCompania, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 120, 30));

        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("FILTRAR POR...");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 372, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laJuegoteca/gui/imgs/fondodesenfocado.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarJuegoActionPerformed
        //Con el botón agregar juego abriremos un diálogo que nos permitirá asignar los atributos a nuestro nuevo objeto Juego.
        DialogoAgregarJuego dialogoAgregarJuego = new DialogoAgregarJuego (this, true); //--> Con este true, NO permitiremos tocar la pantalla principal hasta que cerremos el diálogo.
        dialogoAgregarJuego.setVisible(true);
        refrescarTabla();
    }//GEN-LAST:event_jButtonAgregarJuegoActionPerformed

    private void jButtonGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarDatosActionPerformed
            //Este botón nos permitirá guardar los objetos creados en un archivo .bin para poder importarlos nuevamente a nuestra tabla en caso de que cerremos el programa.
            try{
            LogicaNegocio.escribirFichero();   
            JOptionPane.showMessageDialog(this, "Se han guardado los datos.");
            }
            catch (Exception e) {  //Como estamos manipulando ficheros, debemos utilizar un try-catch, en este caso el catch devuelve un JOPtionPane..
                JOptionPane.showMessageDialog(this, "No se encuentra el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            refrescarTabla();
    }//GEN-LAST:event_jButtonGuardarDatosActionPerformed

    private void TítuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TítuloActionPerformed
        //Uno de los filtros. En este caso podemos filtrar por título (usando la columna 0).
        RowFilter<DefaultTableModel, Integer> rf = RowFilter.regexFilter(jTextFiltrar.getText(), 0);
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_TítuloActionPerformed

    private void jButtonCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarDatosActionPerformed
        //Similar al botón guardar datos, este nos lee un fichero ya creado e importa los datos a la tabla.
        //NO he conseguido limpiar la tabla antes de importar los datos, pero lo he intentado con varios métodos. (en caso de no haber cerrado el programa antes de importar y tener datos en tabla).
        try {
            LogicaNegocio.leerFichero();
            JOptionPane.showMessageDialog(this, "Fichero cargado con éxito.");
        }
        catch (IOException ex) { //De nuevo, como estamos manipulando archivos, un catch.
                JOptionPane.showMessageDialog(this, "No se encuentra el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        refrescarTabla();
    }//GEN-LAST:event_jButtonCargarDatosActionPerformed

    private void jButtonFPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFPlataformaActionPerformed
        //Otro de los botones para filtrar. En este caso, filtramos por plataforma.
        RowFilter<DefaultTableModel, Integer> rf = RowFilter.regexFilter(jTextFiltrar.getText(), 2);
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_jButtonFPlataformaActionPerformed

    private void jButtonFGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFGeneroActionPerformed
        //Botón para filtrar por género.
        RowFilter<DefaultTableModel, Integer> rf = RowFilter.regexFilter(jTextFiltrar.getText(), 1);
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_jButtonFGeneroActionPerformed

    private void jButtonFCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFCompaniaActionPerformed
        //Por último, un botón para filtrar por compañía. No he incluido un botón para filtrar por fecha ya que me resultaba demasiado ambiguo.
        RowFilter<DefaultTableModel, Integer> rf = RowFilter.regexFilter(jTextFiltrar.getText(), 3);
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_jButtonFCompaniaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose(); //Este botón simplemente cierra la aplicación.
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAgregarJuegoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonAgregarJuegoFocusGained

    }//GEN-LAST:event_jButtonAgregarJuegoFocusGained

    private void jButtonAgregarJuegoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarJuegoMouseEntered
        
    }//GEN-LAST:event_jButtonAgregarJuegoMouseEntered

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
            jButtonSalir.setBackground(Color.RED); //Un action listener que cambiará el color del fondo a rojo si pasamos el ratón por encima.
    }//GEN-LAST:event_jButtonSalirMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Título;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregarJuego;
    private javax.swing.JButton jButtonCargarDatos;
    private javax.swing.JButton jButtonFCompania;
    private javax.swing.JButton jButtonFGenero;
    private javax.swing.JButton jButtonFPlataforma;
    private javax.swing.JButton jButtonGuardarDatos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableJuegos;
    private javax.swing.JTextField jTextFiltrar;
    // End of variables declaration//GEN-END:variables
}
